defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: root

development:
  <<: *defaults
  database: TeacherProject_development

test:
  <<: *defaults
  database: TeacherProject_test
